name: Clone wycheproof
description: Clones the wycheproof repository

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      with:
        repository: "google/wycheproof"
        path: "wycheproof"
        ref: "master"
