name: Clone wycheproof
description: Clones the wycheproof repository

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      with:
        repository: "google/wycheproof"
        path: "wycheproof"
        ref: "master"
