[package]
name = "cryptography-cffi"
version = "0.1.0"
authors = ["The cryptography developers <cryptography-dev@python.org>"]
edition = "2021"
publish = false
# This specifies the MSRV
rust-version = "1.63.0"

[dependencies]
pyo3 = { version = "0.19", features = ["abi3-py37"] }
openssl-sys = "0.9.91"

[build-dependencies]
cc = "1.0.83"
